# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-python-deployment
  labels:
    app: my-first-python
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-first-python
  template:
    metadata:
      labels:
        app: my-first-python
    spec:
      containers:
      - name: my-first-python
        image: workshopmoolshankar.azurecr.io/my-py-app:v1
        ports:
        - containerPort: 5003
          name: my-first-python
      imagePullSecrets:
      - name: regcred
---
# Service Definition
apiVersion: v1
kind: Service
metadata:
  name: my-first-python-svc
  labels:
    apps: my-first-python
spec:
  selector:
    app: my-first-python
  type: LoadBalancer
  ports:
    - port: 5003
      name: http
      targetPort: 5003